const EN = {
  "config.title": "API configuration",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Checking saved sign-in…",
  "config.signedOut": "Sign in to OrangeAPI",
  "config.connected": "Connected",
  "config.interrupted": "Connection interrupted",
  "config.email": "Email",
  "config.password": "Password",
  "config.showPassword": "Show password",
  "config.hidePassword": "Hide password",
  "config.remember": "Remember sign-in",
  "config.login": "Sign in",
  "config.loggingIn": "Signing in…",
  "config.logout": "Sign out",
  "config.refresh": "Refresh",
  "config.refreshing": "Refreshing…",
  "config.empty": "No OpenAI API keys",
  "config.stale": "Showing the last available list. Refresh failed.",
  "config.retry": "Retry",
  "config.status.active": "Active",
  "config.status.inactive": "Inactive",
  "config.status.quotaExhausted": "Quota exhausted",
  "config.status.expired": "Expired",
  "config.group": "Group",
  "config.quota": "Quota",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Expires",
  "config.unlimited": "Unlimited",
  "config.noExpiry": "No expiry",
  "config.enabled": "Enabled",
  "config.importCcs": "Import to CCS",
  "config.importingCcs": "Importing…",
  "config.writeLocal": "Write to computer",
  "config.writingLocal": "Writing…",
  "config.confirm.title": "Replace local Codex configuration?",
  "config.confirm.body": "Back up and replace config.toml and auth.json with this key.",
  "config.confirm.closeWarning": "If Codex is running, it will close before either file is changed.",
  "config.confirm.action": "Back up and replace",
  "config.confirm.cancel": "Cancel",
  "config.backupPath": "Backup location",
  "config.ccsSent": "Sent to CC Switch",
  "config.writeSuccess": "Local Codex configuration is enabled and verified.",
  "config.writeRestored": "The write failed. The original files were restored and verified.",
  "config.recoveryRequired": "Automatic recovery failed. Restore the files from this backup.",
  "config.restart": "Restart Codex",
  "config.restarting": "Restarting…",
  "config.restartFailed": "Codex could not be restarted. Try again.",
  "config.account": "Account",
  "config.host": "Service",
  "config.previous": "Previous",
  "config.next": "Next",
  "config.page": "Page {current} of {total}",
  "config.rememberWarning": "Signed in, but the refresh token could not be saved securely.",
  "config.error.desktopRequired": "Open the desktop app to use API configuration.",
  "config.error.invalidCredentials": "The email or password is incorrect.",
  "config.error.forbidden": "This account is not allowed to perform that action.",
  "config.error.rateLimited": "Too many requests. Try again shortly.",
  "config.error.timeout": "The service took too long to respond.",
  "config.error.network": "OrangeAPI could not be reached. Check the network or proxy.",
  "config.error.invalidResponse": "OrangeAPI returned an invalid response.",
  "config.error.apiRejected": "OrangeAPI rejected the request.",
  "config.error.twoFactorUnsupported": "Two-step verification is not supported in this version.",
  "config.error.turnstileUnsupported": "Turnstile verification is not supported in this version.",
  "config.error.credentialStore": "The secure credential store is unavailable.",
  "config.error.signedOut": "The session has expired. Sign in again.",
  "config.error.keyUnavailable": "This API key is no longer available. Refresh the list.",
  "config.error.persistence": "Sign-in metadata could not be saved.",
  "config.error.unsupportedPlatform": "This action is not supported on this platform.",
  "config.error.providerPathUnavailable": "The local Codex configuration path is unavailable.",
  "config.error.providerUnsafeDestination": "The local Codex destination is unsafe and was not changed.",
  "config.error.providerBusy": "Another local configuration write is already running.",
  "config.error.providerEmptyKey": "The selected API key is empty.",
  "config.error.providerIo": "The local Codex files could not be updated.",
  "config.error.ccsUnavailable": "CC Switch is not installed or could not be opened.",
  "config.error.unknown": "The operation failed. Try again.",
} as const;

export type ApiConfigCopyKey = keyof typeof EN;
type ApiConfigCopy = Record<ApiConfigCopyKey, string>;

const ZH_CN: ApiConfigCopy = {
  "config.title": "API 配置",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "正在检查已保存的登录…",
  "config.signedOut": "登录 OrangeAPI",
  "config.connected": "已连接",
  "config.interrupted": "连接已中断",
  "config.email": "邮箱",
  "config.password": "密码",
  "config.showPassword": "显示密码",
  "config.hidePassword": "隐藏密码",
  "config.remember": "记住登录",
  "config.login": "登录",
  "config.loggingIn": "正在登录…",
  "config.logout": "退出登录",
  "config.refresh": "刷新",
  "config.refreshing": "正在刷新…",
  "config.empty": "没有 OpenAI API 密钥",
  "config.stale": "刷新失败，当前显示上次获取的列表。",
  "config.retry": "重试",
  "config.status.active": "可用",
  "config.status.inactive": "停用",
  "config.status.quotaExhausted": "额度已用尽",
  "config.status.expired": "已过期",
  "config.group": "分组",
  "config.quota": "额度",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "到期时间",
  "config.unlimited": "不限额度",
  "config.noExpiry": "永不过期",
  "config.enabled": "已启用",
  "config.importCcs": "导入 CCS",
  "config.importingCcs": "正在导入…",
  "config.writeLocal": "写入本机",
  "config.writingLocal": "正在写入…",
  "config.confirm.title": "覆盖本机 Codex 配置？",
  "config.confirm.body": "将先备份，再使用此密钥完整覆盖 config.toml 和 auth.json。",
  "config.confirm.closeWarning": "如果 Codex 正在运行，会在修改任何文件前正常退出。",
  "config.confirm.action": "备份并覆盖",
  "config.confirm.cancel": "取消",
  "config.backupPath": "备份位置",
  "config.ccsSent": "已发送到 CC Switch",
  "config.writeSuccess": "本机 Codex 配置已启用并通过验证。",
  "config.writeRestored": "写入失败，原文件已恢复并通过验证。",
  "config.recoveryRequired": "自动恢复失败，请使用此备份手动恢复文件。",
  "config.restart": "重启 Codex",
  "config.restarting": "正在重启…",
  "config.restartFailed": "无法重启 Codex，请重试。",
  "config.account": "账号",
  "config.host": "服务",
  "config.previous": "上一页",
  "config.next": "下一页",
  "config.page": "第 {current} / {total} 页",
  "config.rememberWarning": "登录成功，但刷新令牌未能安全保存。",
  "config.error.desktopRequired": "请在桌面客户端中使用 API 配置。",
  "config.error.invalidCredentials": "邮箱或密码不正确。",
  "config.error.forbidden": "当前账号无权执行此操作。",
  "config.error.rateLimited": "请求过于频繁，请稍后重试。",
  "config.error.timeout": "服务响应超时。",
  "config.error.network": "无法连接 OrangeAPI，请检查网络或代理设置。",
  "config.error.invalidResponse": "OrangeAPI 返回了无效响应。",
  "config.error.apiRejected": "OrangeAPI 拒绝了此请求。",
  "config.error.twoFactorUnsupported": "当前版本暂不支持两步验证。",
  "config.error.turnstileUnsupported": "当前版本暂不支持 Turnstile 验证。",
  "config.error.credentialStore": "系统安全凭据存储不可用。",
  "config.error.signedOut": "登录已过期，请重新登录。",
  "config.error.keyUnavailable": "此 API 密钥已不可用，请刷新列表。",
  "config.error.persistence": "无法保存登录信息。",
  "config.error.unsupportedPlatform": "当前平台不支持此操作。",
  "config.error.providerPathUnavailable": "无法获取本机 Codex 配置路径。",
  "config.error.providerUnsafeDestination": "本机 Codex 配置目标不安全，未进行修改。",
  "config.error.providerBusy": "另一项本机配置写入正在进行。",
  "config.error.providerEmptyKey": "所选 API 密钥为空。",
  "config.error.providerIo": "无法更新本机 Codex 配置文件。",
  "config.error.ccsUnavailable": "未安装 CC Switch，或无法将其打开。",
  "config.error.unknown": "操作失败，请重试。",
};

const ZH_TW: ApiConfigCopy = {
  "config.title": "API 設定",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "正在檢查已儲存的登入…",
  "config.signedOut": "登入 OrangeAPI",
  "config.connected": "已連線",
  "config.interrupted": "連線已中斷",
  "config.email": "電子郵件",
  "config.password": "密碼",
  "config.showPassword": "顯示密碼",
  "config.hidePassword": "隱藏密碼",
  "config.remember": "記住登入",
  "config.login": "登入",
  "config.loggingIn": "正在登入…",
  "config.logout": "登出",
  "config.refresh": "重新整理",
  "config.refreshing": "正在重新整理…",
  "config.empty": "沒有 OpenAI API 金鑰",
  "config.stale": "重新整理失敗，目前顯示上次取得的清單。",
  "config.retry": "重試",
  "config.status.active": "可用",
  "config.status.inactive": "停用",
  "config.status.quotaExhausted": "額度已用盡",
  "config.status.expired": "已過期",
  "config.group": "群組",
  "config.quota": "額度",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "到期時間",
  "config.unlimited": "無限額度",
  "config.noExpiry": "永不過期",
  "config.enabled": "已啟用",
  "config.importCcs": "匯入 CCS",
  "config.importingCcs": "正在匯入…",
  "config.writeLocal": "寫入本機",
  "config.writingLocal": "正在寫入…",
  "config.confirm.title": "覆寫本機 Codex 設定？",
  "config.confirm.body": "將先備份，再使用此金鑰完整覆寫 config.toml 與 auth.json。",
  "config.confirm.closeWarning": "若 Codex 正在執行，會在修改任何檔案前正常結束。",
  "config.confirm.action": "備份並覆寫",
  "config.confirm.cancel": "取消",
  "config.backupPath": "備份位置",
  "config.ccsSent": "已傳送到 CC Switch",
  "config.writeSuccess": "本機 Codex 設定已啟用並通過驗證。",
  "config.writeRestored": "寫入失敗，原始檔案已還原並通過驗證。",
  "config.recoveryRequired": "自動還原失敗，請使用此備份手動還原檔案。",
  "config.restart": "重新啟動 Codex",
  "config.restarting": "正在重新啟動…",
  "config.restartFailed": "無法重新啟動 Codex，請重試。",
  "config.account": "帳號",
  "config.host": "服務",
  "config.previous": "上一頁",
  "config.next": "下一頁",
  "config.page": "第 {current} / {total} 頁",
  "config.rememberWarning": "登入成功，但重新整理權杖未能安全儲存。",
  "config.error.desktopRequired": "請在桌面應用程式中使用 API 設定。",
  "config.error.invalidCredentials": "電子郵件或密碼不正確。",
  "config.error.forbidden": "目前帳號無權執行此操作。",
  "config.error.rateLimited": "要求過於頻繁，請稍後重試。",
  "config.error.timeout": "服務回應逾時。",
  "config.error.network": "無法連線 OrangeAPI，請檢查網路或代理伺服器。",
  "config.error.invalidResponse": "OrangeAPI 傳回了無效回應。",
  "config.error.apiRejected": "OrangeAPI 拒絕了此要求。",
  "config.error.twoFactorUnsupported": "目前版本暫不支援兩步驟驗證。",
  "config.error.turnstileUnsupported": "目前版本暫不支援 Turnstile 驗證。",
  "config.error.credentialStore": "系統安全憑證儲存空間不可用。",
  "config.error.signedOut": "登入已過期，請重新登入。",
  "config.error.keyUnavailable": "此 API 金鑰已不可用，請重新整理清單。",
  "config.error.persistence": "無法儲存登入資訊。",
  "config.error.unsupportedPlatform": "目前平台不支援此操作。",
  "config.error.providerPathUnavailable": "無法取得本機 Codex 設定路徑。",
  "config.error.providerUnsafeDestination": "本機 Codex 設定目標不安全，未進行修改。",
  "config.error.providerBusy": "另一項本機設定寫入正在進行。",
  "config.error.providerEmptyKey": "所選 API 金鑰為空。",
  "config.error.providerIo": "無法更新本機 Codex 設定檔。",
  "config.error.ccsUnavailable": "未安裝 CC Switch，或無法將其開啟。",
  "config.error.unknown": "操作失敗，請重試。",
};

const JA: ApiConfigCopy = {
  "config.title": "API 設定",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "保存済みのログインを確認しています…",
  "config.signedOut": "OrangeAPI にログイン",
  "config.connected": "接続済み",
  "config.interrupted": "接続が中断されました",
  "config.email": "メールアドレス",
  "config.password": "パスワード",
  "config.showPassword": "パスワードを表示",
  "config.hidePassword": "パスワードを隠す",
  "config.remember": "ログインを記憶する",
  "config.login": "ログイン",
  "config.loggingIn": "ログイン中…",
  "config.logout": "ログアウト",
  "config.refresh": "更新",
  "config.refreshing": "更新中…",
  "config.empty": "OpenAI API キーがありません",
  "config.stale": "更新に失敗しました。前回取得した一覧を表示しています。",
  "config.retry": "再試行",
  "config.status.active": "有効",
  "config.status.inactive": "無効",
  "config.status.quotaExhausted": "上限に達しました",
  "config.status.expired": "期限切れ",
  "config.group": "グループ",
  "config.quota": "上限",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "有効期限",
  "config.unlimited": "無制限",
  "config.noExpiry": "期限なし",
  "config.enabled": "使用中",
  "config.importCcs": "CCS にインポート",
  "config.importingCcs": "インポート中…",
  "config.writeLocal": "このコンピューターに書き込む",
  "config.writingLocal": "書き込み中…",
  "config.confirm.title": "ローカルの Codex 設定を置き換えますか？",
  "config.confirm.body": "バックアップ後、このキーで config.toml と auth.json を完全に置き換えます。",
  "config.confirm.closeWarning": "Codex が実行中の場合、ファイルを変更する前に正常終了します。",
  "config.confirm.action": "バックアップして置き換える",
  "config.confirm.cancel": "キャンセル",
  "config.backupPath": "バックアップ先",
  "config.ccsSent": "CC Switch に送信しました",
  "config.writeSuccess": "ローカルの Codex 設定を有効化し、検証しました。",
  "config.writeRestored": "書き込みに失敗しました。元のファイルは復元・検証済みです。",
  "config.recoveryRequired": "自動復元に失敗しました。このバックアップから手動で復元してください。",
  "config.restart": "Codex を再起動",
  "config.restarting": "再起動中…",
  "config.restartFailed": "Codex を再起動できませんでした。再試行してください。",
  "config.account": "アカウント",
  "config.host": "サービス",
  "config.previous": "前へ",
  "config.next": "次へ",
  "config.page": "{current} / {total} ページ",
  "config.rememberWarning": "ログインしましたが、更新トークンを安全に保存できませんでした。",
  "config.error.desktopRequired": "API 設定はデスクトップアプリで使用してください。",
  "config.error.invalidCredentials": "メールアドレスまたはパスワードが正しくありません。",
  "config.error.forbidden": "このアカウントには操作権限がありません。",
  "config.error.rateLimited": "リクエストが多すぎます。しばらくしてから再試行してください。",
  "config.error.timeout": "サービスの応答がタイムアウトしました。",
  "config.error.network": "OrangeAPI に接続できません。ネットワークまたはプロキシを確認してください。",
  "config.error.invalidResponse": "OrangeAPI から無効な応答が返されました。",
  "config.error.apiRejected": "OrangeAPI がリクエストを拒否しました。",
  "config.error.twoFactorUnsupported": "このバージョンは二段階認証に対応していません。",
  "config.error.turnstileUnsupported": "このバージョンは Turnstile 認証に対応していません。",
  "config.error.credentialStore": "安全な認証情報ストアを利用できません。",
  "config.error.signedOut": "セッションの有効期限が切れました。再度ログインしてください。",
  "config.error.keyUnavailable": "この API キーは利用できません。一覧を更新してください。",
  "config.error.persistence": "ログイン情報を保存できませんでした。",
  "config.error.unsupportedPlatform": "このプラットフォームでは操作できません。",
  "config.error.providerPathUnavailable": "ローカルの Codex 設定パスを取得できません。",
  "config.error.providerUnsafeDestination": "Codex の保存先が安全でないため、変更しませんでした。",
  "config.error.providerBusy": "別のローカル設定書き込みが実行中です。",
  "config.error.providerEmptyKey": "選択した API キーが空です。",
  "config.error.providerIo": "ローカルの Codex 設定ファイルを更新できませんでした。",
  "config.error.ccsUnavailable": "CC Switch が未インストール、または開けませんでした。",
  "config.error.unknown": "操作に失敗しました。再試行してください。",
};

const KO: ApiConfigCopy = {
  "config.title": "API 구성",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "저장된 로그인 확인 중…",
  "config.signedOut": "OrangeAPI 로그인",
  "config.connected": "연결됨",
  "config.interrupted": "연결이 중단됨",
  "config.email": "이메일",
  "config.password": "비밀번호",
  "config.showPassword": "비밀번호 표시",
  "config.hidePassword": "비밀번호 숨기기",
  "config.remember": "로그인 기억",
  "config.login": "로그인",
  "config.loggingIn": "로그인 중…",
  "config.logout": "로그아웃",
  "config.refresh": "새로 고침",
  "config.refreshing": "새로 고치는 중…",
  "config.empty": "OpenAI API 키가 없습니다",
  "config.stale": "새로 고침에 실패해 마지막으로 가져온 목록을 표시합니다.",
  "config.retry": "다시 시도",
  "config.status.active": "활성",
  "config.status.inactive": "비활성",
  "config.status.quotaExhausted": "할당량 소진",
  "config.status.expired": "만료됨",
  "config.group": "그룹",
  "config.quota": "할당량",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "만료일",
  "config.unlimited": "무제한",
  "config.noExpiry": "만료 없음",
  "config.enabled": "사용 중",
  "config.importCcs": "CCS로 가져오기",
  "config.importingCcs": "가져오는 중…",
  "config.writeLocal": "이 컴퓨터에 쓰기",
  "config.writingLocal": "쓰는 중…",
  "config.confirm.title": "로컬 Codex 구성을 교체할까요?",
  "config.confirm.body": "백업한 뒤 이 키로 config.toml과 auth.json을 완전히 교체합니다.",
  "config.confirm.closeWarning": "Codex가 실행 중이면 파일을 변경하기 전에 정상 종료합니다.",
  "config.confirm.action": "백업 후 교체",
  "config.confirm.cancel": "취소",
  "config.backupPath": "백업 위치",
  "config.ccsSent": "CC Switch로 보냈습니다",
  "config.writeSuccess": "로컬 Codex 구성을 활성화하고 확인했습니다.",
  "config.writeRestored": "쓰기에 실패했습니다. 원본 파일을 복원하고 확인했습니다.",
  "config.recoveryRequired": "자동 복원에 실패했습니다. 이 백업에서 수동으로 복원하세요.",
  "config.restart": "Codex 다시 시작",
  "config.restarting": "다시 시작하는 중…",
  "config.restartFailed": "Codex를 다시 시작할 수 없습니다. 다시 시도하세요.",
  "config.account": "계정",
  "config.host": "서비스",
  "config.previous": "이전",
  "config.next": "다음",
  "config.page": "{current} / {total} 페이지",
  "config.rememberWarning": "로그인했지만 새로 고침 토큰을 안전하게 저장하지 못했습니다.",
  "config.error.desktopRequired": "API 구성은 데스크톱 앱에서 사용하세요.",
  "config.error.invalidCredentials": "이메일 또는 비밀번호가 올바르지 않습니다.",
  "config.error.forbidden": "이 계정에는 해당 작업 권한이 없습니다.",
  "config.error.rateLimited": "요청이 너무 많습니다. 잠시 후 다시 시도하세요.",
  "config.error.timeout": "서비스 응답 시간이 초과되었습니다.",
  "config.error.network": "OrangeAPI에 연결할 수 없습니다. 네트워크 또는 프록시를 확인하세요.",
  "config.error.invalidResponse": "OrangeAPI가 잘못된 응답을 반환했습니다.",
  "config.error.apiRejected": "OrangeAPI가 요청을 거부했습니다.",
  "config.error.twoFactorUnsupported": "이 버전은 2단계 인증을 지원하지 않습니다.",
  "config.error.turnstileUnsupported": "이 버전은 Turnstile 인증을 지원하지 않습니다.",
  "config.error.credentialStore": "보안 자격 증명 저장소를 사용할 수 없습니다.",
  "config.error.signedOut": "세션이 만료되었습니다. 다시 로그인하세요.",
  "config.error.keyUnavailable": "이 API 키를 사용할 수 없습니다. 목록을 새로 고치세요.",
  "config.error.persistence": "로그인 정보를 저장할 수 없습니다.",
  "config.error.unsupportedPlatform": "현재 플랫폼에서는 이 작업을 지원하지 않습니다.",
  "config.error.providerPathUnavailable": "로컬 Codex 구성 경로를 사용할 수 없습니다.",
  "config.error.providerUnsafeDestination": "Codex 대상 경로가 안전하지 않아 변경하지 않았습니다.",
  "config.error.providerBusy": "다른 로컬 구성 쓰기가 진행 중입니다.",
  "config.error.providerEmptyKey": "선택한 API 키가 비어 있습니다.",
  "config.error.providerIo": "로컬 Codex 구성 파일을 업데이트할 수 없습니다.",
  "config.error.ccsUnavailable": "CC Switch가 설치되지 않았거나 열 수 없습니다.",
  "config.error.unknown": "작업에 실패했습니다. 다시 시도하세요.",
};

const FR: ApiConfigCopy = {
  "config.title": "Configuration API",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Vérification de la connexion enregistrée…",
  "config.signedOut": "Se connecter à OrangeAPI",
  "config.connected": "Connecté",
  "config.interrupted": "Connexion interrompue",
  "config.email": "E-mail",
  "config.password": "Mot de passe",
  "config.showPassword": "Afficher le mot de passe",
  "config.hidePassword": "Masquer le mot de passe",
  "config.remember": "Mémoriser la connexion",
  "config.login": "Se connecter",
  "config.loggingIn": "Connexion…",
  "config.logout": "Se déconnecter",
  "config.refresh": "Actualiser",
  "config.refreshing": "Actualisation…",
  "config.empty": "Aucune clé API OpenAI",
  "config.stale": "Échec de l’actualisation. La dernière liste disponible est affichée.",
  "config.retry": "Réessayer",
  "config.status.active": "Active",
  "config.status.inactive": "Inactive",
  "config.status.quotaExhausted": "Quota épuisé",
  "config.status.expired": "Expirée",
  "config.group": "Groupe",
  "config.quota": "Quota",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Expiration",
  "config.unlimited": "Illimité",
  "config.noExpiry": "Sans expiration",
  "config.enabled": "Activée",
  "config.importCcs": "Importer dans CCS",
  "config.importingCcs": "Importation…",
  "config.writeLocal": "Écrire sur cet ordinateur",
  "config.writingLocal": "Écriture…",
  "config.confirm.title": "Remplacer la configuration Codex locale ?",
  "config.confirm.body": "Sauvegarde puis remplace entièrement config.toml et auth.json avec cette clé.",
  "config.confirm.closeWarning": "Si Codex est ouvert, il se fermera avant toute modification de fichier.",
  "config.confirm.action": "Sauvegarder et remplacer",
  "config.confirm.cancel": "Annuler",
  "config.backupPath": "Emplacement de sauvegarde",
  "config.ccsSent": "Envoyé à CC Switch",
  "config.writeSuccess": "La configuration Codex locale est activée et vérifiée.",
  "config.writeRestored": "L’écriture a échoué. Les fichiers d’origine ont été restaurés et vérifiés.",
  "config.recoveryRequired": "La restauration automatique a échoué. Restaurez depuis cette sauvegarde.",
  "config.restart": "Redémarrer Codex",
  "config.restarting": "Redémarrage…",
  "config.restartFailed": "Impossible de redémarrer Codex. Réessayez.",
  "config.account": "Compte",
  "config.host": "Service",
  "config.previous": "Précédent",
  "config.next": "Suivant",
  "config.page": "Page {current} sur {total}",
  "config.rememberWarning": "Connexion réussie, mais le jeton d’actualisation n’a pas pu être stocké de façon sécurisée.",
  "config.error.desktopRequired": "Ouvrez l’application de bureau pour utiliser la configuration API.",
  "config.error.invalidCredentials": "L’e-mail ou le mot de passe est incorrect.",
  "config.error.forbidden": "Ce compte n’est pas autorisé à effectuer cette action.",
  "config.error.rateLimited": "Trop de requêtes. Réessayez dans un instant.",
  "config.error.timeout": "Le service a mis trop de temps à répondre.",
  "config.error.network": "OrangeAPI est inaccessible. Vérifiez le réseau ou le proxy.",
  "config.error.invalidResponse": "OrangeAPI a renvoyé une réponse non valide.",
  "config.error.apiRejected": "OrangeAPI a refusé la requête.",
  "config.error.twoFactorUnsupported": "La vérification en deux étapes n’est pas prise en charge dans cette version.",
  "config.error.turnstileUnsupported": "La vérification Turnstile n’est pas prise en charge dans cette version.",
  "config.error.credentialStore": "Le stockage sécurisé des identifiants est indisponible.",
  "config.error.signedOut": "La session a expiré. Reconnectez-vous.",
  "config.error.keyUnavailable": "Cette clé API n’est plus disponible. Actualisez la liste.",
  "config.error.persistence": "Les informations de connexion n’ont pas pu être enregistrées.",
  "config.error.unsupportedPlatform": "Cette action n’est pas prise en charge sur cette plateforme.",
  "config.error.providerPathUnavailable": "Le chemin de configuration Codex locale est indisponible.",
  "config.error.providerUnsafeDestination": "La destination Codex locale n’est pas sûre et n’a pas été modifiée.",
  "config.error.providerBusy": "Une autre écriture de configuration locale est en cours.",
  "config.error.providerEmptyKey": "La clé API sélectionnée est vide.",
  "config.error.providerIo": "Les fichiers Codex locaux n’ont pas pu être mis à jour.",
  "config.error.ccsUnavailable": "CC Switch n’est pas installé ou n’a pas pu être ouvert.",
  "config.error.unknown": "L’opération a échoué. Réessayez.",
};

const DE: ApiConfigCopy = {
  "config.title": "API-Konfiguration",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Gespeicherte Anmeldung wird geprüft…",
  "config.signedOut": "Bei OrangeAPI anmelden",
  "config.connected": "Verbunden",
  "config.interrupted": "Verbindung unterbrochen",
  "config.email": "E-Mail",
  "config.password": "Passwort",
  "config.showPassword": "Passwort anzeigen",
  "config.hidePassword": "Passwort ausblenden",
  "config.remember": "Anmeldung merken",
  "config.login": "Anmelden",
  "config.loggingIn": "Anmeldung…",
  "config.logout": "Abmelden",
  "config.refresh": "Aktualisieren",
  "config.refreshing": "Wird aktualisiert…",
  "config.empty": "Keine OpenAI-API-Schlüssel",
  "config.stale": "Aktualisierung fehlgeschlagen. Die letzte verfügbare Liste wird angezeigt.",
  "config.retry": "Erneut versuchen",
  "config.status.active": "Aktiv",
  "config.status.inactive": "Inaktiv",
  "config.status.quotaExhausted": "Kontingent aufgebraucht",
  "config.status.expired": "Abgelaufen",
  "config.group": "Gruppe",
  "config.quota": "Kontingent",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Ablauf",
  "config.unlimited": "Unbegrenzt",
  "config.noExpiry": "Kein Ablauf",
  "config.enabled": "Aktiviert",
  "config.importCcs": "In CCS importieren",
  "config.importingCcs": "Wird importiert…",
  "config.writeLocal": "Auf diesen Computer schreiben",
  "config.writingLocal": "Wird geschrieben…",
  "config.confirm.title": "Lokale Codex-Konfiguration ersetzen?",
  "config.confirm.body": "Sichert und ersetzt config.toml und auth.json vollständig mit diesem Schlüssel.",
  "config.confirm.closeWarning": "Wenn Codex läuft, wird es vor jeder Dateiänderung ordnungsgemäß beendet.",
  "config.confirm.action": "Sichern und ersetzen",
  "config.confirm.cancel": "Abbrechen",
  "config.backupPath": "Sicherungsort",
  "config.ccsSent": "An CC Switch gesendet",
  "config.writeSuccess": "Die lokale Codex-Konfiguration ist aktiviert und geprüft.",
  "config.writeRestored": "Schreiben fehlgeschlagen. Die Originaldateien wurden wiederhergestellt und geprüft.",
  "config.recoveryRequired": "Automatische Wiederherstellung fehlgeschlagen. Stellen Sie diese Sicherung manuell wieder her.",
  "config.restart": "Codex neu starten",
  "config.restarting": "Neustart…",
  "config.restartFailed": "Codex konnte nicht neu gestartet werden. Versuchen Sie es erneut.",
  "config.account": "Konto",
  "config.host": "Dienst",
  "config.previous": "Zurück",
  "config.next": "Weiter",
  "config.page": "Seite {current} von {total}",
  "config.rememberWarning": "Angemeldet, aber das Aktualisierungstoken konnte nicht sicher gespeichert werden.",
  "config.error.desktopRequired": "Öffnen Sie die Desktop-App, um die API-Konfiguration zu verwenden.",
  "config.error.invalidCredentials": "E-Mail oder Passwort ist falsch.",
  "config.error.forbidden": "Dieses Konto darf diese Aktion nicht ausführen.",
  "config.error.rateLimited": "Zu viele Anfragen. Versuchen Sie es gleich erneut.",
  "config.error.timeout": "Der Dienst hat nicht rechtzeitig geantwortet.",
  "config.error.network": "OrangeAPI ist nicht erreichbar. Prüfen Sie Netzwerk oder Proxy.",
  "config.error.invalidResponse": "OrangeAPI hat eine ungültige Antwort zurückgegeben.",
  "config.error.apiRejected": "OrangeAPI hat die Anfrage abgelehnt.",
  "config.error.twoFactorUnsupported": "Zwei-Schritt-Verifizierung wird in dieser Version nicht unterstützt.",
  "config.error.turnstileUnsupported": "Turnstile-Verifizierung wird in dieser Version nicht unterstützt.",
  "config.error.credentialStore": "Der sichere Anmeldedatenspeicher ist nicht verfügbar.",
  "config.error.signedOut": "Die Sitzung ist abgelaufen. Melden Sie sich erneut an.",
  "config.error.keyUnavailable": "Dieser API-Schlüssel ist nicht mehr verfügbar. Aktualisieren Sie die Liste.",
  "config.error.persistence": "Anmeldeinformationen konnten nicht gespeichert werden.",
  "config.error.unsupportedPlatform": "Diese Aktion wird auf dieser Plattform nicht unterstützt.",
  "config.error.providerPathUnavailable": "Der lokale Codex-Konfigurationspfad ist nicht verfügbar.",
  "config.error.providerUnsafeDestination": "Das lokale Codex-Ziel ist unsicher und wurde nicht geändert.",
  "config.error.providerBusy": "Eine andere lokale Konfiguration wird bereits geschrieben.",
  "config.error.providerEmptyKey": "Der ausgewählte API-Schlüssel ist leer.",
  "config.error.providerIo": "Die lokalen Codex-Dateien konnten nicht aktualisiert werden.",
  "config.error.ccsUnavailable": "CC Switch ist nicht installiert oder konnte nicht geöffnet werden.",
  "config.error.unknown": "Der Vorgang ist fehlgeschlagen. Versuchen Sie es erneut.",
};

const ES: ApiConfigCopy = {
  "config.title": "Configuración de API",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Comprobando el inicio de sesión guardado…",
  "config.signedOut": "Iniciar sesión en OrangeAPI",
  "config.connected": "Conectado",
  "config.interrupted": "Conexión interrumpida",
  "config.email": "Correo electrónico",
  "config.password": "Contraseña",
  "config.showPassword": "Mostrar contraseña",
  "config.hidePassword": "Ocultar contraseña",
  "config.remember": "Recordar inicio de sesión",
  "config.login": "Iniciar sesión",
  "config.loggingIn": "Iniciando sesión…",
  "config.logout": "Cerrar sesión",
  "config.refresh": "Actualizar",
  "config.refreshing": "Actualizando…",
  "config.empty": "No hay claves API de OpenAI",
  "config.stale": "La actualización falló. Se muestra la última lista disponible.",
  "config.retry": "Reintentar",
  "config.status.active": "Activa",
  "config.status.inactive": "Inactiva",
  "config.status.quotaExhausted": "Cuota agotada",
  "config.status.expired": "Caducada",
  "config.group": "Grupo",
  "config.quota": "Cuota",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Caducidad",
  "config.unlimited": "Ilimitada",
  "config.noExpiry": "Sin caducidad",
  "config.enabled": "Activada",
  "config.importCcs": "Importar a CCS",
  "config.importingCcs": "Importando…",
  "config.writeLocal": "Escribir en este equipo",
  "config.writingLocal": "Escribiendo…",
  "config.confirm.title": "¿Reemplazar la configuración local de Codex?",
  "config.confirm.body": "Crea una copia y reemplaza por completo config.toml y auth.json con esta clave.",
  "config.confirm.closeWarning": "Si Codex está abierto, se cerrará antes de cambiar cualquier archivo.",
  "config.confirm.action": "Crear copia y reemplazar",
  "config.confirm.cancel": "Cancelar",
  "config.backupPath": "Ubicación de la copia",
  "config.ccsSent": "Enviado a CC Switch",
  "config.writeSuccess": "La configuración local de Codex está activada y verificada.",
  "config.writeRestored": "La escritura falló. Los archivos originales se restauraron y verificaron.",
  "config.recoveryRequired": "La recuperación automática falló. Restaura los archivos desde esta copia.",
  "config.restart": "Reiniciar Codex",
  "config.restarting": "Reiniciando…",
  "config.restartFailed": "No se pudo reiniciar Codex. Inténtalo de nuevo.",
  "config.account": "Cuenta",
  "config.host": "Servicio",
  "config.previous": "Anterior",
  "config.next": "Siguiente",
  "config.page": "Página {current} de {total}",
  "config.rememberWarning": "Se inició sesión, pero el token de actualización no pudo guardarse de forma segura.",
  "config.error.desktopRequired": "Abre la aplicación de escritorio para usar la configuración de API.",
  "config.error.invalidCredentials": "El correo o la contraseña son incorrectos.",
  "config.error.forbidden": "Esta cuenta no puede realizar esa acción.",
  "config.error.rateLimited": "Demasiadas solicitudes. Inténtalo de nuevo en breve.",
  "config.error.timeout": "El servicio tardó demasiado en responder.",
  "config.error.network": "No se pudo conectar con OrangeAPI. Comprueba la red o el proxy.",
  "config.error.invalidResponse": "OrangeAPI devolvió una respuesta no válida.",
  "config.error.apiRejected": "OrangeAPI rechazó la solicitud.",
  "config.error.twoFactorUnsupported": "Esta versión no admite la verificación en dos pasos.",
  "config.error.turnstileUnsupported": "Esta versión no admite la verificación Turnstile.",
  "config.error.credentialStore": "El almacén seguro de credenciales no está disponible.",
  "config.error.signedOut": "La sesión ha caducado. Inicia sesión de nuevo.",
  "config.error.keyUnavailable": "Esta clave API ya no está disponible. Actualiza la lista.",
  "config.error.persistence": "No se pudo guardar la información de inicio de sesión.",
  "config.error.unsupportedPlatform": "Esta acción no es compatible con esta plataforma.",
  "config.error.providerPathUnavailable": "La ruta de configuración local de Codex no está disponible.",
  "config.error.providerUnsafeDestination": "El destino local de Codex no es seguro y no se modificó.",
  "config.error.providerBusy": "Ya hay otra escritura de configuración local en curso.",
  "config.error.providerEmptyKey": "La clave API seleccionada está vacía.",
  "config.error.providerIo": "No se pudieron actualizar los archivos locales de Codex.",
  "config.error.ccsUnavailable": "CC Switch no está instalado o no pudo abrirse.",
  "config.error.unknown": "La operación falló. Inténtalo de nuevo.",
};

const PT_BR: ApiConfigCopy = {
  "config.title": "Configuração de API",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Verificando o login salvo…",
  "config.signedOut": "Entrar no OrangeAPI",
  "config.connected": "Conectado",
  "config.interrupted": "Conexão interrompida",
  "config.email": "E-mail",
  "config.password": "Senha",
  "config.showPassword": "Mostrar senha",
  "config.hidePassword": "Ocultar senha",
  "config.remember": "Lembrar login",
  "config.login": "Entrar",
  "config.loggingIn": "Entrando…",
  "config.logout": "Sair",
  "config.refresh": "Atualizar",
  "config.refreshing": "Atualizando…",
  "config.empty": "Nenhuma chave de API OpenAI",
  "config.stale": "A atualização falhou. A última lista disponível está sendo exibida.",
  "config.retry": "Tentar novamente",
  "config.status.active": "Ativa",
  "config.status.inactive": "Inativa",
  "config.status.quotaExhausted": "Cota esgotada",
  "config.status.expired": "Expirada",
  "config.group": "Grupo",
  "config.quota": "Cota",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Validade",
  "config.unlimited": "Ilimitada",
  "config.noExpiry": "Sem validade",
  "config.enabled": "Ativada",
  "config.importCcs": "Importar para CCS",
  "config.importingCcs": "Importando…",
  "config.writeLocal": "Gravar neste computador",
  "config.writingLocal": "Gravando…",
  "config.confirm.title": "Substituir a configuração local do Codex?",
  "config.confirm.body": "Faz backup e substitui completamente config.toml e auth.json por esta chave.",
  "config.confirm.closeWarning": "Se o Codex estiver aberto, ele será fechado antes de qualquer arquivo ser alterado.",
  "config.confirm.action": "Fazer backup e substituir",
  "config.confirm.cancel": "Cancelar",
  "config.backupPath": "Local do backup",
  "config.ccsSent": "Enviado ao CC Switch",
  "config.writeSuccess": "A configuração local do Codex foi ativada e verificada.",
  "config.writeRestored": "A gravação falhou. Os arquivos originais foram restaurados e verificados.",
  "config.recoveryRequired": "A recuperação automática falhou. Restaure os arquivos deste backup.",
  "config.restart": "Reiniciar o Codex",
  "config.restarting": "Reiniciando…",
  "config.restartFailed": "Não foi possível reiniciar o Codex. Tente novamente.",
  "config.account": "Conta",
  "config.host": "Serviço",
  "config.previous": "Anterior",
  "config.next": "Próxima",
  "config.page": "Página {current} de {total}",
  "config.rememberWarning": "Login concluído, mas o token de atualização não pôde ser salvo com segurança.",
  "config.error.desktopRequired": "Abra o aplicativo para desktop para usar a configuração de API.",
  "config.error.invalidCredentials": "O e-mail ou a senha está incorreto.",
  "config.error.forbidden": "Esta conta não pode executar essa ação.",
  "config.error.rateLimited": "Muitas solicitações. Tente novamente em instantes.",
  "config.error.timeout": "O serviço demorou demais para responder.",
  "config.error.network": "Não foi possível acessar o OrangeAPI. Verifique a rede ou o proxy.",
  "config.error.invalidResponse": "O OrangeAPI retornou uma resposta inválida.",
  "config.error.apiRejected": "O OrangeAPI rejeitou a solicitação.",
  "config.error.twoFactorUnsupported": "A verificação em duas etapas não é compatível com esta versão.",
  "config.error.turnstileUnsupported": "A verificação Turnstile não é compatível com esta versão.",
  "config.error.credentialStore": "O armazenamento seguro de credenciais não está disponível.",
  "config.error.signedOut": "A sessão expirou. Entre novamente.",
  "config.error.keyUnavailable": "Esta chave de API não está mais disponível. Atualize a lista.",
  "config.error.persistence": "Não foi possível salvar as informações de login.",
  "config.error.unsupportedPlatform": "Esta ação não é compatível com esta plataforma.",
  "config.error.providerPathUnavailable": "O caminho da configuração local do Codex não está disponível.",
  "config.error.providerUnsafeDestination": "O destino local do Codex não é seguro e não foi alterado.",
  "config.error.providerBusy": "Outra gravação da configuração local já está em andamento.",
  "config.error.providerEmptyKey": "A chave de API selecionada está vazia.",
  "config.error.providerIo": "Não foi possível atualizar os arquivos locais do Codex.",
  "config.error.ccsUnavailable": "O CC Switch não está instalado ou não pôde ser aberto.",
  "config.error.unknown": "A operação falhou. Tente novamente.",
};

const RU: ApiConfigCopy = {
  "config.title": "Настройка API",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "Проверка сохранённого входа…",
  "config.signedOut": "Войти в OrangeAPI",
  "config.connected": "Подключено",
  "config.interrupted": "Соединение прервано",
  "config.email": "Электронная почта",
  "config.password": "Пароль",
  "config.showPassword": "Показать пароль",
  "config.hidePassword": "Скрыть пароль",
  "config.remember": "Запомнить вход",
  "config.login": "Войти",
  "config.loggingIn": "Вход…",
  "config.logout": "Выйти",
  "config.refresh": "Обновить",
  "config.refreshing": "Обновление…",
  "config.empty": "Нет ключей API OpenAI",
  "config.stale": "Обновить не удалось. Показан последний доступный список.",
  "config.retry": "Повторить",
  "config.status.active": "Активен",
  "config.status.inactive": "Неактивен",
  "config.status.quotaExhausted": "Лимит исчерпан",
  "config.status.expired": "Истёк",
  "config.group": "Группа",
  "config.quota": "Лимит",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "Срок действия",
  "config.unlimited": "Без ограничений",
  "config.noExpiry": "Без срока",
  "config.enabled": "Используется",
  "config.importCcs": "Импортировать в CCS",
  "config.importingCcs": "Импорт…",
  "config.writeLocal": "Записать на компьютер",
  "config.writingLocal": "Запись…",
  "config.confirm.title": "Заменить локальную конфигурацию Codex?",
  "config.confirm.body": "Создаёт резервную копию и полностью заменяет config.toml и auth.json этим ключом.",
  "config.confirm.closeWarning": "Если Codex запущен, он корректно завершится до изменения файлов.",
  "config.confirm.action": "Создать копию и заменить",
  "config.confirm.cancel": "Отмена",
  "config.backupPath": "Расположение копии",
  "config.ccsSent": "Отправлено в CC Switch",
  "config.writeSuccess": "Локальная конфигурация Codex включена и проверена.",
  "config.writeRestored": "Запись не удалась. Исходные файлы восстановлены и проверены.",
  "config.recoveryRequired": "Автовосстановление не удалось. Восстановите файлы из этой копии.",
  "config.restart": "Перезапустить Codex",
  "config.restarting": "Перезапуск…",
  "config.restartFailed": "Не удалось перезапустить Codex. Повторите попытку.",
  "config.account": "Учётная запись",
  "config.host": "Сервис",
  "config.previous": "Назад",
  "config.next": "Далее",
  "config.page": "Страница {current} из {total}",
  "config.rememberWarning": "Вход выполнен, но токен обновления не удалось безопасно сохранить.",
  "config.error.desktopRequired": "Откройте настольное приложение для настройки API.",
  "config.error.invalidCredentials": "Неверная электронная почта или пароль.",
  "config.error.forbidden": "У этой учётной записи нет прав на действие.",
  "config.error.rateLimited": "Слишком много запросов. Повторите немного позже.",
  "config.error.timeout": "Сервис не ответил вовремя.",
  "config.error.network": "OrangeAPI недоступен. Проверьте сеть или прокси.",
  "config.error.invalidResponse": "OrangeAPI вернул недопустимый ответ.",
  "config.error.apiRejected": "OrangeAPI отклонил запрос.",
  "config.error.twoFactorUnsupported": "Двухэтапная проверка не поддерживается в этой версии.",
  "config.error.turnstileUnsupported": "Проверка Turnstile не поддерживается в этой версии.",
  "config.error.credentialStore": "Безопасное хранилище учётных данных недоступно.",
  "config.error.signedOut": "Сеанс истёк. Войдите снова.",
  "config.error.keyUnavailable": "Этот ключ API больше недоступен. Обновите список.",
  "config.error.persistence": "Не удалось сохранить данные входа.",
  "config.error.unsupportedPlatform": "Действие не поддерживается на этой платформе.",
  "config.error.providerPathUnavailable": "Путь локальной конфигурации Codex недоступен.",
  "config.error.providerUnsafeDestination": "Локальное назначение Codex небезопасно и не изменено.",
  "config.error.providerBusy": "Уже выполняется другая запись локальной конфигурации.",
  "config.error.providerEmptyKey": "Выбранный ключ API пуст.",
  "config.error.providerIo": "Не удалось обновить локальные файлы Codex.",
  "config.error.ccsUnavailable": "CC Switch не установлен или не открылся.",
  "config.error.unknown": "Операция не выполнена. Повторите попытку.",
};

const AR: ApiConfigCopy = {
  "config.title": "إعداد API",
  "config.service": "token.cylonai.cn · OpenAI",
  "config.restoring": "جارٍ التحقق من تسجيل الدخول المحفوظ…",
  "config.signedOut": "تسجيل الدخول إلى OrangeAPI",
  "config.connected": "متصل",
  "config.interrupted": "انقطع الاتصال",
  "config.email": "البريد الإلكتروني",
  "config.password": "كلمة المرور",
  "config.showPassword": "إظهار كلمة المرور",
  "config.hidePassword": "إخفاء كلمة المرور",
  "config.remember": "تذكر تسجيل الدخول",
  "config.login": "تسجيل الدخول",
  "config.loggingIn": "جارٍ تسجيل الدخول…",
  "config.logout": "تسجيل الخروج",
  "config.refresh": "تحديث",
  "config.refreshing": "جارٍ التحديث…",
  "config.empty": "لا توجد مفاتيح OpenAI API",
  "config.stale": "فشل التحديث. يتم عرض آخر قائمة متاحة.",
  "config.retry": "إعادة المحاولة",
  "config.status.active": "نشط",
  "config.status.inactive": "غير نشط",
  "config.status.quotaExhausted": "نفدت الحصة",
  "config.status.expired": "منتهي الصلاحية",
  "config.group": "المجموعة",
  "config.quota": "الحصة",
  "config.quotaValue": "{used} / {quota}",
  "config.expiry": "انتهاء الصلاحية",
  "config.unlimited": "غير محدود",
  "config.noExpiry": "بلا انتهاء",
  "config.enabled": "مفعّل",
  "config.importCcs": "استيراد إلى CCS",
  "config.importingCcs": "جارٍ الاستيراد…",
  "config.writeLocal": "الكتابة إلى هذا الكمبيوتر",
  "config.writingLocal": "جارٍ الكتابة…",
  "config.confirm.title": "استبدال إعداد Codex المحلي؟",
  "config.confirm.body": "ينشئ نسخة احتياطية ثم يستبدل config.toml وauth.json بالكامل بهذا المفتاح.",
  "config.confirm.closeWarning": "إذا كان Codex قيد التشغيل فسيُغلق بشكل سليم قبل تغيير أي ملف.",
  "config.confirm.action": "نسخ احتياطي واستبدال",
  "config.confirm.cancel": "إلغاء",
  "config.backupPath": "موقع النسخة الاحتياطية",
  "config.ccsSent": "تم الإرسال إلى CC Switch",
  "config.writeSuccess": "تم تفعيل إعداد Codex المحلي والتحقق منه.",
  "config.writeRestored": "فشلت الكتابة. تمت استعادة الملفات الأصلية والتحقق منها.",
  "config.recoveryRequired": "فشلت الاستعادة التلقائية. استعد الملفات من هذه النسخة الاحتياطية.",
  "config.restart": "إعادة تشغيل Codex",
  "config.restarting": "جارٍ إعادة التشغيل…",
  "config.restartFailed": "تعذرت إعادة تشغيل Codex. حاول مجددًا.",
  "config.account": "الحساب",
  "config.host": "الخدمة",
  "config.previous": "السابق",
  "config.next": "التالي",
  "config.page": "الصفحة {current} من {total}",
  "config.rememberWarning": "تم تسجيل الدخول، لكن تعذر حفظ رمز التحديث بأمان.",
  "config.error.desktopRequired": "افتح تطبيق سطح المكتب لاستخدام إعداد API.",
  "config.error.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "config.error.forbidden": "هذا الحساب غير مخوّل لتنفيذ هذا الإجراء.",
  "config.error.rateLimited": "طلبات كثيرة جدًا. حاول مرة أخرى بعد قليل.",
  "config.error.timeout": "استغرقت الخدمة وقتًا طويلاً للاستجابة.",
  "config.error.network": "تعذر الوصول إلى OrangeAPI. تحقق من الشبكة أو الوكيل.",
  "config.error.invalidResponse": "أعاد OrangeAPI استجابة غير صالحة.",
  "config.error.apiRejected": "رفض OrangeAPI الطلب.",
  "config.error.twoFactorUnsupported": "التحقق بخطوتين غير مدعوم في هذا الإصدار.",
  "config.error.turnstileUnsupported": "تحقق Turnstile غير مدعوم في هذا الإصدار.",
  "config.error.credentialStore": "مخزن بيانات الاعتماد الآمن غير متاح.",
  "config.error.signedOut": "انتهت الجلسة. سجّل الدخول مجددًا.",
  "config.error.keyUnavailable": "مفتاح API هذا لم يعد متاحًا. حدّث القائمة.",
  "config.error.persistence": "تعذر حفظ معلومات تسجيل الدخول.",
  "config.error.unsupportedPlatform": "هذا الإجراء غير مدعوم على هذه المنصة.",
  "config.error.providerPathUnavailable": "مسار إعداد Codex المحلي غير متاح.",
  "config.error.providerUnsafeDestination": "وجهة Codex المحلية غير آمنة ولم يتم تغييرها.",
  "config.error.providerBusy": "تجري كتابة إعداد محلي أخرى بالفعل.",
  "config.error.providerEmptyKey": "مفتاح API المحدد فارغ.",
  "config.error.providerIo": "تعذر تحديث ملفات Codex المحلية.",
  "config.error.ccsUnavailable": "CC Switch غير مثبت أو تعذر فتحه.",
  "config.error.unknown": "فشلت العملية. حاول مجددًا.",
};

export const API_CONFIG_COPY = {
  en: EN,
  "zh-CN": ZH_CN,
  "zh-TW": ZH_TW,
  ja: JA,
  ko: KO,
  fr: FR,
  de: DE,
  es: ES,
  "pt-BR": PT_BR,
  ru: RU,
  ar: AR,
} as const;
